name: Rust

on:
  push:
    branches: [ "main" ]
    paths: 
      - .github/workflows/rust.yml
      - src/**
      - Cargo.toml
      - Cargo.lock
      - build.rs
  pull_request:
    branches: [ "main" ]
    paths: 
      - .github/workflows/rust.yml
      - src/**
      - Cargo.toml
      - Cargo.lock
      - build.rs

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -r --verbose
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: target/release/bitcomet-mod.exe
